[package]
name = "estat"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
mockito = "1.7.0"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tempfile = "3.20.0"
tokio-test = "0.4.4"
