from typing import Any, Optional

class PyEstatClient:
    def __init__(self, api_key: str, base_url: Optional[str] = None) -> None: ...
    def get_stats_list(self, stats_code: str, limit: int) -> str: ...
